### PR TITLE
Adds (possibly) missing file to package

### LINKED ISSUE #12: pip install fails with python 3.6
```
$ pip install pocha
Collecting pocha
  Downloading pocha-0.12.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-p117vgyi/pocha/setup.py", line 32, in <module>
        tests_require=load('requirements-dev.txt'),
      File "/tmp/pip-build-p117vgyi/pocha/setup.py", line 21, in load
        with open(filename, 'r') as input_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements-dev.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-p117vgyi/pocha/
 ```

This is `pip --version`
```
pip 9.0.1 from /home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages (python 3.6)
```

This is `python --version`
```
Python 3.6.1
```

### PR DESCRIPTION
**Pull request by JJ**
(Possibly) fixes #12 

I'm not sure about test-requirements.txt, but that should fail only when packaging...

### CODE REVIEW

**Comment by rlgomes** [comment]
thanks for reporting the issue and supplying a fix!! @JJ

**Comment by rlgomes** [comment]
I'll push out another build in a moment

**Comment by JJ** [comment]
Glad to be of help!

**Comment by rlgomes** [comment]
@JJ https://pypi.python.org/pypi/pocha build 0.13.0 should work, if not lets fix it!

**Comment by JJ** [comment]
Thanks! I'll check it out right now.

**Comment by JJ** [comment]
Like a charm:

😃👏

**Pull request merged**
